# Generated by Django 5.0.9 on 2024-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_rename_running_subscription_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaccount",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
