# Generated by Django 5.0.9 on 2024-09-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="users.customer",
            ),
        ),
    ]
