# Generated by Django 5.0.9 on 2024-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_guest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
    ]
