# Generated by Django 5.0.9 on 2024-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0003_operatingsystem_region_virtualmachine_backup_freq_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualmachine",
            name="name",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
