# Generated by Django 5.0.9 on 2024-09-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_virtualmachine_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backup",
            name="price",
        ),
    ]
