# Generated by Django 5.0.9 on 2024-09-10 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_remove_backup_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2024, 9, 10, 11, 22, 40, 292202, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
