name: Build and Push Docker Images from prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build all the images
      - name: Build Django image
        run: docker build -f ./compose/production/django/Dockerfile -t autovm_production_django:latest .

      - name: Build Postgres image
        run: docker build -f ./compose/production/postgres/Dockerfile -t autovm_production_postgres:latest .

      - name: Build Traefik image
        run: docker build -f ./compose/production/traefik/Dockerfile -t autovm_production_traefik:latest .

      - name: Build CeleryWorker image
        run: docker build -f ./compose/production/django/Dockerfile -t autovm_production_celeryworker:latest .

      - name: Build CeleryBeat image
        run: docker build -f ./compose/production/django/Dockerfile -t autovm_production_celerybeat:latest .

      - name: Build Flower image
        run: docker build -f ./compose/production/django/Dockerfile -t autovm_production_flower:latest .

      - name: Build Nginx image
        run: docker build -f ./compose/production/nginx/Dockerfile -t autovm_production_nginx:latest .

      # Tag all the images
      - name: Tag Django image
        run: docker tag autovm_production_django:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_django:latest

      - name: Tag Postgres image
        run: docker tag autovm_production_postgres:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_postgres:latest

      - name: Tag Traefik image
        run: docker tag autovm_production_traefik:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_traefik:latest

      - name: Tag CeleryWorker image
        run: docker tag autovm_production_celeryworker:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_celeryworker:latest

      - name: Tag CeleryBeat image
        run: docker tag autovm_production_celerybeat:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_celerybeat:latest

      - name: Tag Flower image
        run: docker tag autovm_production_flower:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_flower:latest

      - name: Tag Nginx image
        run: docker tag autovm_production_nginx:latest ${{ secrets.DOCKERHUB_USER }}/autovm_production_nginx:latest

      # Push all
      - name: Push Django image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_django:latest

      - name: Push Postgres image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_postgres:latest

      - name: Push Traefik image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_traefik:latest

      - name: Push CeleryWorker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_celeryworker:latest

      - name: Push CeleryBeat image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_celerybeat:latest

      - name: Push Flower image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_flower:latest

      - name: Push Nginx image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/autovm_production_nginx:latest
